using System;
using System.IO;

namespace Lab1
{
    class Program
    {

        static void Main(string[] args)
        {
            System.Diagnostics.ProcessStartInfo start = new System.Diagnostics.ProcessStartInfo();
            //python interpreter location
            start.FileName = @"/Users/qwysam/.pyenv/shims/python3";
            //argument with file name and input parameters
            start.Arguments = string.Format("{0} {1} {2}", @"/Users/qwysam/repos/Information_Theory/Information-Theory/Lab1/Lab1.py", 5, 10);
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            using (System.Diagnostics.Process process = System.Diagnostics.Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                    Console.WriteLine("From System Diagnostics");
                    Console.WriteLine("5 + 10 = {0}", result);
                }
            }

            Console.ReadLine();
        }
    }
}
